### ISSUE TITLE
Update names of global status bits

### ISSUE THREAD

**Issue by bmkemp910** [DiamondLightSource/dls-pmac-control#32]
In the global status page there are many "(Reserved for future use)" and "(For Internal use)" bits which now have named uses. The display should be updated to show these names.
For the first status word from Y:$6 where bit 0 is the top left indicator on the page and the following bits then list down the left of the page:
Bit 0 is Abort Input
Bit 1 is (Reserved for future use)
Bit 2 is (Reserved for future use)
Bit 3 is Ring Sync Packet Fault
Bit 4 is Ring Break Detected
Bit 5 is Ring Break Message Received
Bit 6 is Clearing FSAVE Flash Sector
Bit 7 is Bad FSAVE Flash Sector
Bit 8 is Modbus Active
Bit 9 is MACRO Ring Active
Bit 10 is MACRO Ring Check Active

All other bits from the two global status words are correctly described.

**Comment by JamesOHeaDLS** [comment]
Descriptions for tooltips taken from Turbo SRM 19-12-12 manual
