### ISSUE TITLE
Move Amp Status bits (7 Segment Display Status) to Global Status or the Main Screen

### ISSUE THREAD

**Issue by JimboMonkey** [DiamondLightSource/dls-pmac-control#7]
At the moment the Amp Status bits (7 Segment Display Status) is found at the bottom of the CS Status screen.  This status is general and doesn't just apply to coordinate systems.  It would be more useful and intuitive for it to be displayed on the Global Status screen, or on the main screen of the program.

Thank you

**Comment by JamesOHeaDLS** [comment]
This is included in the 3.2.2 release
